export const DEVELOPMENT_BLOG_SERVER_BASE_URL = import.meta.env
  .VITE_DEVELOPMENT_BLOG_SERVER_BASE_URL;

export const DEVELOPMENT_STOCK_SERVER_BASE_URL = import.meta.env
  .VITE_DEVELOPMENT_BLOG_SERVER_BASE_URL;

export const MAX_BLOG_TAGS = 10;

export const MAX_BLOG_INTRODUCTION = 300;

export const MAX_BLOG_TITLE = 200;
